# NOTE: Generated By HttpRunner v3.1.11
# FROM: har\erp_demo.har


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase
from testcases.erp_login_test import TestCaseErpDemo as Login
import pytest


class TestCaseErpDemo(HttpRunner):
    config = Config("testcase description").base_url("http://erp2.hzb-it.com/").verify(False).variables(
        **{  # todo: .base_url()设置项目全局地址
            "Host": "erp2.hzb-it.com",
            "Accept": "application/json, text/plain, */*"  # todo：定义全局变量
        })

    teststeps = [
        Step(RunTestCase("login").call(Login).export("data")),  # 先进行系统登录
        Step(
            RunRequest("/app/common/base/enumList")
            .get("http://erp2.hzb-it.com/app/common/base/enumList")
            .with_headers(
                **{
                    "Host": "${Host}",
                    "Accept": "application/json, text/plain, */*",
                    "access-token": "${data}",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36",
                    "Referer": "http://erp2.hzb-it.com/",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                    "Cookie": "access-token=${data}",
                    "Connection": "keep-alive",
                }
            )
            .with_cookies(
                **{
                    "access-token": "${data}"
                }
            )
            .teardown_hook("${sleep(5)}")  # todo:调用debugtalk.py文件方法，执行方法后，等待5s
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json")
        ),
    ]


if __name__ == "__main__":
    # TestCaseErpDemo().test_start()
    pytest.main(['-vs', 'erp_demo_test.py'])
