# NOTE: Generated By HttpRunner v3.1.11
# FROM: har\erp_demo.har


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseErpDemo(HttpRunner):
    config = Config("testcase description").base_url("http://erp2.hzb-it.com/").verify(False).variables(
        **{  # todo: .base_url()设置项目全局地址
            "Host": "erp2.hzb-it.com",
            "Accept": "application/json, text/plain, */*",  # todo：定义全局变量
            "username": "admin",
            "password": "123",
        })

    teststeps = [
        Step(RunRequest("系统登录")
             .with_variables(**{"Content-Length": "27"})  # todo:定义局部变量
             .post("http://erp2.hzb-it.com/app/common/login")
             .with_headers(**{'Host': '${Host}',  # todo: 引用Host变量
                              'Connection': 'keep-alive',
                              'Content-Length': '${Content-Length}',  # todo：引用局部变量
                              'Accept': '${Accept}',  # todo: 引用Accept变量
                              'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36 Edg/113.0.1774.42',
                              'Content-Type': 'application/x-www-form-urlencoded', 'Origin': 'http://erp2.hzb-it.com',
                              'Referer': 'http://erp2.hzb-it.com/', 'Accept-Encoding': 'gzip, deflate',
                              'Accept-Language': 'zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6',
                              'Cookie': 'Hm_lvt_a40372507a0e32054c266b4dce474b80=1684833484; Hm_lpvt_a40372507a0e32054c266b4dce474b80=1684833484'})
             # .with_cookies(**{'Hm_lvt_a40372507a0e32054c266b4dce474b80': '1684833484', 'Hm_lpvt_a40372507a0e32054c266b4dce474b80': '1684833484'})
             .with_data({'username': '$username', 'password': '$password'})
             .extract().with_jmespath("body.data", "data")
             .validate()
             .assert_equal("status_code", 200)
             .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
             .assert_equal("body.msg", "提交成功")
             # .assert_equal("body.data", "eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2ODUwMDYzOTAsInVzZXJEZXRhaWxzIjoie1wicm9sZXNcIjpbe1wiY29kZVwiOlwic3VwZXJhZG1pblwiLFwibmFtZVwiOlwi6LaF57qn566h55CG5ZGYXCIsXCJpZFwiOjF9XSxcIm9yZ0lkXCI6MSxcInBhc3N3b3JkXCI6XCIkMmEkMTAkTkVzck55QklQR0VMeDlEcElibS94LlZ3QU1PemhtWDRjT2ZPNGp6d1JKZjZYaXpZcnhqSTJcIixcImlkZW50aXR5XCI6MSxcIm5hbWVcIjpcIueuoeeQhuWRmFwiLFwiaWRcIjoxLFwic3RhdGVcIjoxLFwidXNlcm5hbWVcIjpcImFkbWluXCJ9In0.EcH7pKun3_-Qe1dX_zv3YN-YzuQIL6QFklG5EHptAKI")
             .assert_equal("body.errCode", 0)),
    ]


if __name__ == "__main__":
    TestCaseErpDemo().test_start()
